# Generated by Django 3.1.2 on 2020-12-03 06:51

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('wodo', '0018_auto_20201203_0646'),
    # ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('artid', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='ArticleID')),
                ('title', models.CharField(default='Article Title', max_length=100)),
                ('location', models.FileField(upload_to=None, verbose_name='File')),
                ('metaTags', jsonfield.fields.JSONField(verbose_name='Meta_Tags')),
            ],
        ),
        migrations.CreateModel(
            name='homeData',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('dataid', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='Data ID')),
                ('regWorker', models.IntegerField(default=5000, verbose_name='Registered Workers')),
                ('customer', models.IntegerField(default=350000, verbose_name='Happy Customers')),
                ('connection', models.IntegerField(default=5000, verbose_name='Connections')),
            ],
        ),
        migrations.CreateModel(
            name='workWithUs',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('ageid', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='Agent ID')),
                ('name', models.CharField(default='User', max_length=100, verbose_name='Name')),
                ('contact', models.IntegerField(default=9630961847, max_length=10, verbose_name='Contact')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=100, verbose_name='Email')),
                ('username', models.CharField(default='shiva12', max_length=200, null=True, verbose_name='Token')),
            ],
        ),
        migrations.CreateModel(
            name='workerRating',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('ratid', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='Review ID')),
                ('rating', models.FloatField(default=5.0, max_length=10, null=True, verbose_name='Ratings')),
                ('review', models.CharField(default='Very good app', max_length=200, null=True, verbose_name='Review')),
                ('name', models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='custRating',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('ratid', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='RatingID')),
                ('rating', models.FloatField(default=5.0, max_length=10, null=True, verbose_name='Ratings')),
                ('review', models.CharField(default='Very good app', max_length=200, null='True', verbose_name='Review')),
                ('name', models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', unique=True, verbose_name='Name')),
            ],
        ),
    ]
