# Generated by Django 3.1.2 on 2020-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='services',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
