# Generated by Django 3.1.2 on 2020-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0002_workers_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='wagestype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
