# Generated by Django 3.1.2 on 2020-11-09 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0004_auto_20201103_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-11-09'),
        ),
        migrations.AddField(
            model_name='hired',
            name='slot',
            field=models.TimeField(default=datetime.datetime(2020, 11, 9, 18, 5, 30, 997600)),
        ),
    ]
