# Generated by Django 3.1.2 on 2020-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0005_auto_20201109_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='slot',
            field=models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING')], max_length=20),
        ),
    ]
