# Generated by Django 3.1.2 on 2020-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0008_auto_20201117_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-11-22'),
        ),
    ]
