# Generated by Django 3.1.2 on 2020-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0009_auto_20201122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED')], default='UPCOMING', max_length=20),
        ),
    ]
