# Generated by Django 3.1.2 on 2020-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0010_auto_20201122_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='hired',
            name='extension',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-11-24'),
        ),
    ]
