# Generated by Django 3.1.2 on 2020-11-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0011_auto_20201124_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='verified',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-11-25'),
        ),
    ]
