# Generated by Django 3.1.2 on 2020-11-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0012_auto_20201125_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-11-27'),
        ),
        migrations.CreateModel(
            name='dutyDenials',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('denyID', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='denialID')),
                ('reason', models.CharField(choices=[('NOT SATISFACTORY', 'NOT SATISFACTORY'), ('WORKER DENIED', 'WORKER DENIED')], max_length=100, null=True)),
                ('transid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wodo.transaction', to_field='transID', verbose_name='transID')),
                ('user', models.ForeignKey(default='specsoid', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='username')),
                ('worker', models.ForeignKey(default='test001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='workerid')),
            ],
        ),
    ]
