# Generated by Django 3.1.2 on 2020-11-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0013_auto_20201127_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='userH',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='hired',
            name='workerIDH',
            field=models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='workerID'),
        ),
        migrations.AlterField(
            model_name='reportworker',
            name='userRe',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reportworker',
            name='workerIDW',
            field=models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='workerID'),
        ),
    ]
