# Generated by Django 3.1.2 on 2020-11-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0014_auto_20201127_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutydenials',
            name='worker',
            field=models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='workerid'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='workerIDS',
            field=models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='workerID'),
        ),
        migrations.AlterField(
            model_name='workrating',
            name='workerIDR',
            field=models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='workerID'),
        ),
    ]
