# Generated by Django 3.1.2 on 2020-11-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0015_auto_20201127_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutydenials',
            name='user',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='filtercache',
            name='userF',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='userS',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='userT',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='workrating',
            name='userR',
            field=models.ForeignKey(default='shiva12', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='User'),
        ),
    ]
