# Generated by Django 3.1.2 on 2020-11-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0016_auto_20201127_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-11-29'),
        ),
        migrations.CreateModel(
            name='workerCalls',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('callID', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True, verbose_name='callID')),
                ('callSid', models.CharField(default='123456', max_length=100)),
                ('record', models.URLField(null=True, verbose_name='CallRecord')),
                ('transid', models.CharField(default='HIR00001', max_length=100)),
                ('userid', models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.appuser', to_field='username', verbose_name='UserID')),
                ('workerid', models.ForeignKey(default='BHO1001', on_delete=django.db.models.deletion.SET_DEFAULT, to='wodo.workers', to_field='workerid', verbose_name='WorkerID')),
            ],
        ),
    ]
