# Generated by Django 3.1.2 on 2020-12-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodo', '0017_auto_20201129_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired',
            name='date',
            field=models.DateField(default='2020-12-03'),
        ),
    ]
